# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: swellaby.mirror-git-repository.mirror-git-repository-vsts-task.mirror-git-repository-vsts-task@1
  displayName: 'Mirror Git Repository'
  inputs:
    sourceGitRepositoryUri: 'https://martin@dev.azure.com/martin/AADWebApp/_git/AADWebApp'
    sourceVerifySSLCertificate: false
    destinationGitRepositoryUri: 'https://github.com/martinwoodward/AADWebApp.git'
    destinationGitRepositoryPersonalAccessToken: '$(GH-PAT)'

